In [11]:
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd


In [12]:
dataset = pd.read_csv(r"C:\Users\AR ANSARI\NIT\ML\vs\ML Classifer\Churn_Modelling.csv")
dataset

apst  CustomerId    Surname  CreditScore  Geography  Gender  Age  \
0         1    15634602   Hargrave          619      delhi  Female   42   
1         2    15647311       Hill          608  bangalore  Female   41   
2         3    15619304       Onio          502      delhi  Female   42   
3         4    15701354       Boni          699      delhi  Female   39   
4         5    15737888   Mitchell          850  bangalore  Female   43   
...     ...         ...        ...          ...        ...     ...  ...   
9995   9996    15606229   Obijiaku          771      delhi    Male   39   
9996   9997    15569892  Johnstone          516      delhi    Male   35   
9997   9998    15584532        Liu          709      delhi  Female   36   
9998   9999    15682355  Sabbatini          772     mumbai    Male   42   
9999  10000    15628319     Walker          792      delhi  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [13]:
x = dataset.iloc[:,3:-1].values
x

array([[619, 'delhi', 'Female', ..., 1, 1, 101348.88],
       [608, 'bangalore', 'Female', ..., 0, 1, 112542.58],
       [502, 'delhi', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'delhi', 'Female', ..., 0, 1, 42085.58],
       [772, 'mumbai', 'Male', ..., 1, 0, 92888.52],
       [792, 'delhi', 'Female', ..., 1, 0, 38190.78]],
      shape=(10000, 10), dtype=object)

In [14]:
y = dataset.iloc[:,-1].values
y

array([1, 0, 1, ..., 1, 1, 0], shape=(10000,))

In [15]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2]= le.fit_transform(x[:,2])

In [16]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2, random_state=0)
x_train,x_test,y_train,y_test

(array([[1.0, 0.0, 0.0, ..., 1, 0, 163830.64],
        [0.0, 0.0, 1.0, ..., 1, 1, 57098.0],
        [0.0, 1.0, 0.0, ..., 1, 0, 185630.76],
        ...,
        [0.0, 1.0, 0.0, ..., 1, 0, 181429.87],
        [1.0, 0.0, 0.0, ..., 1, 1, 148750.16],
        [0.0, 0.0, 1.0, ..., 1, 0, 118855.26]],
       shape=(8000, 12), dtype=object),
 array([[0.0, 0.0, 1.0, ..., 1, 1, 192852.67],
        [0.0, 1.0, 0.0, ..., 1, 0, 128702.1],
        [1.0, 0.0, 0.0, ..., 1, 1, 75732.25],
        ...,
        [1.0, 0.0, 0.0, ..., 1, 0, 141533.19],
        [0.0, 0.0, 1.0, ..., 1, 1, 11276.48],
        [0.0, 0.0, 1.0, ..., 1, 0, 192950.6]],
       shape=(2000, 12), dtype=object),
 array([0, 0, 0, ..., 0, 0, 1], shape=(8000,)),
 array([0, 1, 0, ..., 0, 0, 0], shape=(2000,)))

In [18]:
from xgboost import XGBClassifier
classifier = XGBClassifier(n_estimators=30)
# classifier = XGBClassifier()

classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], shape=(2000,))

In [19]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)


[[1517   78]
 [ 188  217]]


In [20]:

from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test,y_pred)
print(ac)

0.867


In [21]:

from sklearn.metrics import classification_report
cr = classification_report(y_test,y_pred)
print(cr)


              precision    recall  f1-score   support

           0       0.89      0.95      0.92      1595
           1       0.74      0.54      0.62       405

    accuracy                           0.87      2000
   macro avg       0.81      0.74      0.77      2000
weighted avg       0.86      0.87      0.86      2000



In [22]:
bias = classifier.score(x_train, y_train)
print(bias)


0.89975


In [23]:
variance = classifier.score(x_test, y_test)
print(variance)

0.867


In [24]:
# k-fold
from sklearn.model_selection import cross_val_score 
accuracies = cross_val_score(estimator = classifier, X = x_train, y = y_train, cv = 5)
print("Accuracy: {:.2f}%".format(accuracies.mean()*100))

Accuracy: 85.90%
